# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b95e9995a868c662e2dc38ede62d4a1b522381e25c6b208abcef0404d952eef189390d398836537ac4315d541edc412737e9046c639a1fcb8fdcc4252977981e

test:
  secret_key_base: 8d8bf86a9f8aab0538595b6c6b34010a3c9b9f2ba92176d6e887261d5b242c236c5826ca9a5d706827ec11677c6816452b9f1db8b411db9e55caac93cf0d4a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
